trigger:
- main

pr:
- main

pool:
  vmImage: 'windows-latest'

variables:
  - name: 'BuildConfiguration'
    value: 'Release'
    
stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: specific
        project: 'ASP.net_7_RESTful_API'
        pipeline: '3'
        artifactName: 'drop'
        downloadPath: '$(Pipeline.Workspace)/MyApp'

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '3.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
        performMultiLevelLookup: true

    - task: AzureWebApp@1
      displayName: 'Azure Web App Deploy'
      inputs:
        azureSubscription: 'Azure subscription 1'
        appName: 'ASPnet7RESTfulAPI'
        package: '$(Pipeline.Workspace)/MyApp/MyApp.zip'
        deploymentMethod: 'auto'
        appType: 'webApp'
