trigger:
- main

pool:
  vmImage: 'windows-latest'
  workspace:
    clean: all

variables:
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
      performMultiLevelLookup: true

  - script: 'dotnet build --configuration $(buildConfiguration)'
    displayName: 'dotnet build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish $(buildConfiguration)'
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/MyApp' # Added /MyApp

  - task: ArchiveFiles@2
    displayName: 'Create ZIP Artifact'
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/MyApp'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/MyApp/MyApp.zip'
      replaceExistingArchive: true

  - publish: $(Build.ArtifactStagingDirectory)/MyApp/MyApp.zip
    displayName: 'Publish Artifact'
    artifact: drop
